### PR TITLE
Fix all deps

### PR DESCRIPTION
**Pull request by seiferteric**
This PR would use git directly to clone the deps and checks out a specific commit ID for each dep.

### CODE REVIEW

**Comment by renukamanavalan** [comment]
retest this please

**Comment by lguohan** [comment]
retest this please

**Comment by lguohan** [comment]
retest this please

**Comment by lguohan** [comment]
retest this please

**Comment by lguohan** [comment]
retest this please

**Comment by lguohan** [comment]
@seiferteric , thanks for the fix! should we cherry-pick this pr to 201911 branch?

**Comment by pavel-shirshov** [comment]
Just a suggestion to use a standard method in go ecosystem: Use vendoring.
In this case we will store all the dependencies in the repositary and will not depend on the modules repos (they could remove commits, repo or do force-push).
It is supported now in go "go mod vendor"

**Comment by renukamanavalan** [comment]
Thanks Pavel! That is their plan. Expect it in their next PR.

**Pull request merged**
