### PR TITLE
REST Server optimizations

### PR DESCRIPTION
**Pull request by sachinholla**
**- Why I did it**

We observed slow and non-deterministic response times from the mgmt-framework REST server. Profiling revealed hotspots in TLS handshake in go http library and regex evaluation in github.com/gorilla/mux router. This PR addresses these performance issues. It also includes few minor cleanups & fixes required for upcoming PRs.

**- How I did it**

1\) REST server used github.com/gorilla/mux router for matching the request path to registered OpenAPI path template. Mux uses linear regex based path matching, which does not scale for >10k templates. This affects REST server performance when large yangs are deployed.

Yang generated RESTCONF OpenAPI specs do not use regex path templates. Implemented a simple http request router which maintains a tree of RESTCONF path templates and matches the request using a tree search. Each element of the path template is a tree node. Example:

```
 Templates:       Tree:    A         Matched paths:
 /A/B={id}/X             /   \       /A, /A/B, /A/B=1, /A/C
 /A/B={id}/Y          B={id}  C      /A/B=2/X, /A/B=3/Y
 /A/C                 /    \
                     X      Y        Does not match: /B, /A/D
```

Request path elements are iterated left to right while traversing the tree top to bottom. Parameterized path elements are parsed as `<name>=<comma_separated_values>` format (per RESTCONF spec) and names are compared. Only parameter counts (if any) are matched. Syntax checks not done here, it will be validated by translib later.

This simple tree search significantly improves REST server performance and ensures uniform response time irrespective of number of yangs deployed. One of the examples: 68s vs 0.09s to match 1000 requests.

Non-RESTCONF paths (defined by direct OpenAPI specs) continue to get managed thru the existing mux router. RESTCONF paths are identified by the path prefix "/restconf/".

2\) Do not set TLS curve preference while initializing HTTPS server. Old code was setting preference P521,P384,P256. By default go prefers faster X25519 curve. This saved approx 42s for 1000 REST calls.

3\) Changed global auth enable flag as router instance configuration. RBAC code (coming next) will require multiple router instances with different auth modes.

4\) Handle url escaped path param values - like `/ip=10.0.0.1%2f32`. Translib path will be `/ip[10.0.0.1/32]`.

5\) Framework for custom path parameter name to yang key name mapping. Yang allows same key attribute names in parent and child lists. This results in RESTCONF paths with same parameter name at multiple levels. OpenAPI suggests unique parameter names; swagger tools do not support duplicate parameter names. Solution is to generate OpenAPI spec with unique path parameter names and generate a key mapping through OpenAPI extension schema. Key mapping contains assigned name to yang name map. REST server uses it to generate the translib path with proper yang key attribute name.

```
  list AA {                 RESTCONF path: /AA={id}/BB={id}
      key id;               OpenAPI path : /AA={id}/BB={id#2}
      list BB {             Key mappings : { "id#2": "id" }
          key id;
      }                     Request URL  : /AA=1/BB=2
  }                         Translib path: /AA[id=1]/BB[id=2]
```

This commit only includes REST server part of this solution. OpenAPI generator enhancemnets will come later.

6\) Updated go test cases for above enhancements.

7\) Changed swagger UI installation path to `/etc/rest_server/ui`. It can be overridden through command line option -rest_ui for local testing.

**- How to verify it**

Verify ACL related REST calls.
KLISH CLI
Gotest

**- Description for the changelog**

REST Server optimizations

### CODE REVIEW

**Comment by renukamanavalan** [comment]
retest

**Comment by renukamanavalan** [comment]
retest this please

**Comment by sachinholla** [comment]
retest this please

**Comment by sachinholla** [comment]
retest this please

**Comment by renukamanavalan** [comment]
retest this please

**Comment by renukamanavalan** [comment]
retest this please

**Comment by renukamanavalan** [comment]
retest this please

**Pull request merged**
